// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyC_4f3BTgYuSGmxnjW3asTYbDAyGCx_PpY',
  //   appId: '1:67565756870:web:6cea2631263dbc099d92c7',
  //   messagingSenderId: '67565756870',
  //   projectId: 'pancake-workshop-app',
  //   authDomain: 'pancake-workshop-app.firebaseapp.com',
  //   storageBucket: 'pancake-workshop-app.firebasestorage.app',
  //   measurementId: 'G-YZBD2HWD7T',
  // );
  //
  // static const FirebaseOptions android = FirebaseOptions(
  //   apiKey: 'AIzaSyCCkNITQDkxmHxjhDwON8eBPgL4M4DIAhQ',
  //   appId: '1:67565756870:android:cf9603b919097b659d92c7',
  //   messagingSenderId: '67565756870',
  //   projectId: 'pancake-workshop-app',
  //   storageBucket: 'pancake-workshop-app.firebasestorage.app',
  // );
  //
  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyCmuYCMa6YVYNTOulTcQZVHxMw1o-efLzc',
  //   appId: '1:67565756870:ios:ec7c484e0c22e58f9d92c7',
  //   messagingSenderId: '67565756870',
  //   projectId: 'pancake-workshop-app',
  //   storageBucket: 'pancake-workshop-app.firebasestorage.app',
  //   iosBundleId: 'com.example.flutterFinalProject',
  // );
  //
  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyCmuYCMa6YVYNTOulTcQZVHxMw1o-efLzc',
  //   appId: '1:67565756870:ios:ec7c484e0c22e58f9d92c7',
  //   messagingSenderId: '67565756870',
  //   projectId: 'pancake-workshop-app',
  //   storageBucket: 'pancake-workshop-app.firebasestorage.app',
  //   iosBundleId: 'com.example.flutterFinalProject',
  // );
  //
  // static const FirebaseOptions windows = FirebaseOptions(
  //   apiKey: 'AIzaSyC_4f3BTgYuSGmxnjW3asTYbDAyGCx_PpY',
  //   appId: '1:67565756870:web:6f2d4bb1f656a08c9d92c7',
  //   messagingSenderId: '67565756870',
  //   projectId: 'pancake-workshop-app',
  //   authDomain: 'pancake-workshop-app.firebaseapp.com',
  //   storageBucket: 'pancake-workshop-app.firebasestorage.app',
  //   measurementId: 'G-45SV7VLNHK',
  // );

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: dotenv.env['WEB_API_KEY']!,
    appId: dotenv.env['WEB_APP_ID']!,
    messagingSenderId: dotenv.env['MESSAGING_SENDER_ID']!,
    projectId: dotenv.env['PROJECT_ID']!,
    authDomain: dotenv.env['AUTH_DOMAIN']!,
    storageBucket: dotenv.env['STORAGE_BUCKET']!,
    measurementId: dotenv.env['MEASUREMENT_ID']!,
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.env['ANDROID_API_KEY']!,
    appId: dotenv.env['ANDROID_APP_ID']!,
    messagingSenderId: dotenv.env['MESSAGING_SENDER_ID']!,
    projectId: dotenv.env['PROJECT_ID']!,
    storageBucket: dotenv.env['STORAGE_BUCKET']!,
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.env['IOS_API_KEY']!,
    appId: dotenv.env['IOS_APP_ID']!,
    messagingSenderId: dotenv.env['MESSAGING_SENDER_ID']!,
    projectId: dotenv.env['PROJECT_ID']!,
    storageBucket: dotenv.env['STORAGE_BUCKET']!,
    iosBundleId: dotenv.env['IOS_BUNDLE_ID']!,
  );

  static FirebaseOptions get macos => ios;

  static FirebaseOptions get windows => web;
}
